// An educational single-cylinder engine. Dimensions are illustrative, not CAD tolerances.
export const PARTS = [
  { id: 'plug', name: 'Spark plug', material: 'Ceramic · nickel alloy', description: 'An electrical spark ignites the compressed air–fuel mixture at the end of the compression stroke.', instruction: 'Unscrew the spark plug from the cylinder head.', position: [.48, 3.48, .55], offset: [2.1, 2.1, 1.2], anchor: [0, .35, 0] },
  { id: 'cover', name: 'Rocker cover', material: 'Powder-coated aluminium', description: 'Protects the rocker arms and retains the oil that lubricates the valve mechanism. Its fasteners travel with the cover in this model.', instruction: 'Lift the cover and its fasteners to expose the valve train.', position: [0, 3.99, 0], offset: [0, 3.8, 0], anchor: [0, .18, 0] },
  { id: 'rockers', name: 'Valve train', material: 'Hardened steel', description: 'Rocker arms open the intake and exhaust valves. Springs return each valve to its seat. Timing is simplified for this demonstration.', instruction: 'Lift out the grouped rockers, valves, and return springs.', position: [0, 3.52, 0], offset: [-2.3, 2.7, 0], anchor: [0, .15, 0] },
  { id: 'head', name: 'Cylinder head', material: 'Cast aluminium', description: 'Closes the combustion chamber and contains the valve passages and spark plug port. Cooling fins transfer heat to the surrounding air.', instruction: 'Lift the head clear of the cylinder.', position: [0, 3.34, 0], offset: [0, 2.45, 0], anchor: [.65, 0, .25] },
  { id: 'barrel', name: 'Cylinder barrel', material: 'Aluminium · iron liner', description: 'The piston slides inside this hollow, finned cylinder. The liner guides its motion while the fins increase the surface area for cooling.', instruction: 'Slide the barrel up and to the left to reveal the piston.', position: [0, 2.53, 0], offset: [-2.45, 1.35, 0], anchor: [-.7, 0, 0] },
  { id: 'piston', name: 'Piston & wrist pin', material: 'Aluminium · steel rings', description: 'Gas pressure pushes the piston downward. Its rings seal the cylinder, and the wrist pin connects it to the connecting rod.', instruction: 'Withdraw the grouped wrist pin and lift the piston off the rod.', position: [0, 2.62, 0], offset: [2.25, 1.55, 0], anchor: [.48, .2, 0] },
  { id: 'flywheel', name: 'Flywheel', material: 'Machined steel', description: 'Stores rotational energy to carry the crankshaft between power strokes. The simplified spokes also make the rotation easy to see.', instruction: 'Pull the flywheel from the rear of the crankshaft.', position: [0, 1, -1.12], offset: [0, 0, -3.25], anchor: [-.9, .3, 0] },
  { id: 'case-front', name: 'Crankcase cover', material: 'Cast aluminium', description: 'Seals the front of the crankcase and supports the crankshaft bearing. Remove it to reach the connecting rod and crankshaft.', instruction: 'Remove the front cover and its captive fasteners.', position: [0, 1, .59], offset: [0, 0, 3.1], anchor: [.65, .2, .15] },
  { id: 'rod', name: 'Connecting rod', material: 'Forged steel', description: 'Links the piston to the offset crank pin, converting the piston’s reciprocating motion into crankshaft rotation.', instruction: 'Release the big end and withdraw the rod from the crank pin.', position: [0, 1.42, 0], offset: [2.5, .2, .65], anchor: [.1, .65, .12] },
  { id: 'crank', name: 'Crankshaft', material: 'Forged steel', description: 'The offset crank pin turns the piston’s linear motion into rotation. Counterweights balance the moving assembly.', instruction: 'Slide the crankshaft out of its remaining bearing.', position: [0, 1, 0], offset: [-2.4, -.15, 1.15], anchor: [-.5, 0, .4] },
  { id: 'case', name: 'Crankcase & base', material: 'Cast aluminium', description: 'The fixed foundation supports the cylinder and crankshaft. It stays on the workbench while the ten removable assemblies are explored.', instruction: 'This is the fixed foundation of the engine.', position: [0, 1, 0], offset: [0, 0, 0], anchor: [-.8, -.45, .2], fixed: true },
];
export const REMOVABLE = PARTS.filter(p => !p.fixed);
export const partById = id => PARTS.find(p => p.id === id);
export const clamp = (v, min = 0, max = 1) => Math.max(min, Math.min(max, v));
